"""empty message

Revision ID: 4ad118ac2c45
Revises: d2f7e1cb27ad
Create Date: 2024-10-06 18:24:57.108778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad118ac2c45'
down_revision = 'd2f7e1cb27ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
