"""Basic google sign-up -- test1

Revision ID: d2f7e1cb27ad
Revises: e7e391fea2f0
Create Date: 2024-09-08 09:16:09.000821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2f7e1cb27ad'
down_revision = 'e7e391fea2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
